# Generated by Django 5.1.4 on 2024-12-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_field',
        ),
    ]
